# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style) '
style = 'bold purple'

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ & ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[ & ](bold red)'

[username]
show_always = true
format = '[$user]($style)@'

[directory]
read_only = ' ğŸ”’'
truncation_symbol = 'â€¦/'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


